config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :favorites, only: [:create, :destroy, :show]
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :instaclos do
      collection do
      post :confirm
      end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :instaclo
end

app/models/instaclo.rb
class Instaclo < ApplicationRecord
    validates :content, presence: true, length: { in: 1..140 }
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :instaclos, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_instaclos, through: :favorites, source: :instaclo
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        ContactMailer.contact_mail(@contact).deliver
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def show
    @favorites_instaclos = current_user.favorite_instaclos
  end
  
  def create
    favorite = current_user.favorites.create(instaclo_id: params[:instaclo_id])
    redirect_to instaclos_url, notice: "#{favorite.instaclo.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to instaclos_url, notice: "#{favorite.instaclo.user.name}さんの投稿をお気に入り解除しました"
  end
end

app/controllers/instaclos_controller.rb
class InstaclosController < ApplicationController
before_action :set_instaclo, only: [:show, :edit, :update, :destroy]
before_action :session_twiclo, only: [:edit, :update, :destroy, :create, :new, :index]
  
  def index
    @instaclos = Instaclo.all
  end
  
  def new
    if params[:back]
      @instaclo = Instaclo.new(instaclo_params)
    else
      @instaclo = Instaclo.new
    end
  end
  
  def create
    @instaclo = Instaclo.new(instaclo_params)
    @instaclo.user_id = current_user.id
    if @instaclo.save
      redirect_to instaclos_path, notice: "投稿しました！"
      ContactMailer.contact_mail(@instaclo,@instaclo.user.email).deliver
    else
      render 'new'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(instaclo_id: @instaclo.id)
  end
  
  def edit
  end

  def update
    if @instaclo.update(instaclo_params)
      redirect_to instaclos_path, notice: "編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @instaclo.destroy
    redirect_to instaclos_path, notice:"削除しました！"
  end
  
  def confirm
    @instaclo = Instaclo.new(instaclo_params)
    @instaclo.user_id = current_user.id
    render :new if @instaclo.invalid?
  end
  
  private
  def instaclo_params
    params.require(:instaclo).permit(:content, :image, :image_cache)
  end

  def set_instaclo
    @instaclo = Instaclo.find(params[:id])
  end

  def session_twiclo
    if logged_in?
    else
      render new_session_path  
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path(@user.id)
    else
      render 'new'
    end
  end

  def show
     @user = User.find(params[:id])
     @favorites_instaclos = @user.favorite_instaclos
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,
                                 :image, :image_cache, )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/instaclos_helper.rb
module InstaclosHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_instaclos_path
    elsif action_name == 'edit'
      instaclo_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :contact_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/favorites/show.html.erb
<h1>お気に入り一覧</h1>
<table>
　<% @favorites_instaclos.each do |instaclo| %>
  <tr>
      <td>投稿者:<%= instaclo.user.name %>さん<br>
          <%= image_tag instaclo.user.image_url (:thumb) %></td>
      <td><%= image_tag instaclo.image %></td>
      <td>コメント:<%= instaclo.content %><br>
      <button type="button" class="btn btn-success btn-sm">
        <%= link_to '詳細', instaclo_path(instaclo.id) %></button>
  </tr>
  <% end %>
</table>

app/views/instaclos/_form.html.erb
<%= form_with(model: @instaclo, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @instaclo.errors.any? %>
    <div id="error_explanation">
      <h2><%= @instaclo.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @instaclo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="instaclo_title">
    <%= form.label :コメント %>
    <%= form.text_field :content %>
  </div>
  <div class="instaclo_title">
    <%= form.label :画像 %>
    <%= form.file_field :image, id: :instaclo_image %>
  </div>
  <br>
  <button type="submit" class="btn btn-warning btn-sm">投稿</button>
<% end %>

app/views/instaclos/confirm.html.erb
<h3>以下の内容で、投稿しますか？</h3>

<%= form_with(model: @instaclo, url: instaclos_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>コメント:<%= @instaclo.content %></p>
  <p>画像:<%= image_tag(@instaclo.image) %></p>
  <%= form.hidden_field :image_cache %>
  <button type="submit" class="btn btn-warning btn-sm">投稿</button>
<% end %>

<br>

<%= form_with(model: @instaclo, url: new_instaclo_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <button type="submit" name='back' class="btn btn-default btn-sm">もどる</button>
<% end %>

app/views/instaclos/edit.html.erb
  <h2>編集する</h2>

  <%= render 'form' %>

app/views/instaclos/index.html.erb
<h1>投稿一覧</h1>

<table>
<% @instaclos.each do |instaclo| %>

  <tr>

    <td>投稿者:<%= instaclo.user.name %>さん<br>
        <%= image_tag instaclo.user.image_url (:thumb) %></td>
    <td><%= image_tag instaclo.image %></td>
    <td>コメント:<%= instaclo.content %><br>
      <button type="button" class="btn btn-success btn-sm">
        <%= link_to '詳細', instaclo_path(instaclo.id) %></button>
    <% if instaclo.user_id == current_user.id %>
      <button type="button" class="btn btn-primary btn-sm">
        <%= link_to '編集', edit_instaclo_path(instaclo.id), data: { confirm: '本当に編集していいですか？' } %></button>
      <button type="button" class="btn btn-danger btn-sm">
        <%= link_to '削除', instaclo_path(instaclo.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></button></td>
    <% end %>

  </tr>

<% end %>
</table>

app/views/instaclos/new.html.erb
  <h2>新規投稿する</h2>

  <%= render 'form' %>

app/views/instaclos/show.html.erb
<h1>詳細画面</h1>

<p>投稿画像: </p><br>
<%= image_tag @instaclo.image %>
<p>内容: <%= @instaclo.content %></p>

<% unless @instaclo.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(instaclo_id: @instaclo.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="normalize.css">
    <link rel="stylesheet" href="instaclos.scss">

    <meta name="viewport" content="width=device-width">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

<body>
  <header>
          <% if logged_in? %>
          <button type="button" class="btn btn-info btn-sm">
             <%= link_to "ログアウト", session_path(current_user.id), method: :delete %></button>
          <button type="button" class="btn btn-info btn-sm">
             <%= link_to "プロフィール", user_path(current_user.id) %></button>
          <% else %>
          <button type="button" class="btn btn-info btn-sm">
             <%= link_to "ログイン", new_session_path %></button>
          <button type="button" class="btn btn-info btn-sm">
             <%= link_to "新規ユーザー登録", new_user_path %></button>
          <% end %>
          <button type="button" class="btn btn-warning btn-sm">
            <%= link_to "投稿一覧", instaclos_path %></button>
          <button type="button" class="btn btn-warning btn-sm">
            <%= link_to '新規投稿', new_instaclo_path %></button>
           
  </header>
  <section class="main-header">
    <%= image_tag "top7.png" %>
  </section>

  <div class="content">
  <h2><%= notice %></h2>
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>新規ユーザー登録</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>

  <%= f.label :お名前 %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :パスワード %>
  <%= f.password_field :password %>

  <%= f.label :パスワード（再入力） %>
  <%= f.password_field :password_confirmation %>
  
  <br><br>
  <%=f.label :image,"ユーザーアイコン画像" %>
  <%= f.file_field :image %>
  
  <br>
  
  <button type="f.submit" class="btn btn-default btn-sm">新規登録</button>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>
<p>ユーザーアイコン画像</p><br>
<%= image_tag(@user.image.url) if @user.image.url %>

<br><br>
<button type="button" class="btn btn-warning btn-sm">
    <%= link_to 'お気に入り一覧', favorite_path %>
</button>